test-obj-y+=test_scale_angle
test-obj-y+=test_mem_store
test-obj-y+=test_network_shell
test-obj-y+=face_test
test-obj-y+=test_detect
test-obj-y+=test_align
test-obj-y+=test_detectAccuracy
test-obj-y+=test_detect_for_lightenedCNN
test-obj-y+=test_lightenedCNN

TEST_LIBS+=-lpthread
